#!/usr/bin/env python3
 
import json
 
dir = "~/.cache/wal/colors.json"
input = "~/.config/zathura/zathurarc_template"
output = "~/.config/zathura/zathurarc"
with open(dir) as json_data:
    d = json.load(json_data)
    bg = d["special"]["background"]
    fg = d["special"]["foreground"]
fin = open(input)
fout = open(output, "w")
for line in fin:
    l = line.replace("FG",fg).replace("BG",bg)
    fout.write( l )
fin.close()
fout.close()
